version: '2'
services:
    appfusion-app:
        image: appfusion
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://appfusion-mysql:3306/appfusion?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=appfusion-elasticsearch:9300
        ports:
            - 8080:8080
    appfusion-mysql:
        extends:
            file: mysql.yml
            service: appfusion-mysql
    appfusion-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: appfusion-elasticsearch
